export const TEXTOS_CONTRATO = {
  es: {
    titulo: "CONTRATO DE ALQUILER DE MOTOCICLETA",
    nombreCliente: "Nombre del Cliente:",
    pasaporte: "#Pasaporte/ID:",
    telefono: "Teléfono:",
    hotel: "Hotel de Estadía:",
    s1: "1. Términos de Alquiler",
    s1txt: "El Arrendador acuerda alquilar al Arrendatario la motocicleta bajo las siguientes condiciones:",
    marcaModelo: "Marca/Modelo:",
    placa: "Número de Placa:",
    horaAlquiler: "Hora de Entrega:",
    fechaAlquiler: "Fecha de Alquiler:",
    fechaDevolucion: "Fecha de Devolución:",
    tarifaAplicada: "Tarifa Aplicada:",
    usd: "USD",
    totalEstimado: "Total a pagar:",
    reglaDia: "Tarifa del día",
    reglaEspecial: "Tarifa especial (entrega después de las 2:00 pm)",
    reglaNocturno: "Tarifa nocturna ($10.00) + tarifa del día siguiente",
    reglaPorDias: (n) => `Tarifa por día × ${n} día${n === 1 ? "" : "s"}`,
    reglaPorDiasConEspecial: (n) => `Tarifa especial el primer día + tarifa normal los siguientes ${n - 1} día${n - 1 === 1 ? "" : "s"}`,
    s2: "2. Uso y Responsabilidad del Arrendatario",
    s2intro: "El Arrendatario se compromete a:",
    s2items: [
      "Utilizar la motocicleta de manera responsable y segura.",
      "Respetar todas las normas de tránsito y regulaciones locales.",
      "No conducir la motocicleta bajo la influencia de bebidas alcohólicas o sustancias prohibidas.",
      "Utilizar siempre el casco proporcionado por el Arrendador.",
      "No permitir que otra persona conduzca la motocicleta sin autorización previa del Arrendador.",
      "No participar en carreras, competencias o actividades peligrosas con la motocicleta.",
      "No utilizar la motocicleta en terrenos inadecuados que puedan causar daños mecánicos o estructurales.",
    ],
    s3: "3. Responsabilidad por Daños, Multas y Pérdida",
    s3items: [
      "El Arrendatario es responsable de cualquier daño, pérdida o desperfecto que sufra la motocicleta durante el periodo de alquiler, debiendo asumir los costos de reparación o reemplazo según corresponda.",
      "El Arrendatario será responsable de cualquier multa, sanción o amonestación impuesta por las autoridades de tránsito debido a infracciones cometidas durante el uso de la motocicleta.",
      "En caso de accidente, el Arrendatario deberá informar de inmediato al Arrendador y a las autoridades correspondientes.",
    ],
    s4: "4. Devolución de la Motocicleta",
    s4items: [
      "La motocicleta debe ser devuelta en el mismo estado en que fue recibida, en la fecha y hora acordadas.",
      "En caso de retraso en la devolución, se aplicarán cargos adicionales según la tarifa de alquiler.",
    ],
    s5: "5. Exoneración de Responsabilidad del Arrendador",
    s5items: [
      "El Arrendador no se hace responsable de ningún accidente, lesión o daño sufrido por el Arrendatario o terceros durante el uso de la motocicleta.",
      "El Arrendatario exonera al Arrendador de cualquier reclamación o acción legal derivada del uso de la motocicleta.",
    ],
    s6: "6. Firma y Aceptación",
    s6txt: "Al firmar este contrato, el Arrendatario acepta haber leído y comprendido todos los términos y condiciones aquí descritos y se compromete a cumplirlos.",
    firmaCliente: "Firma del Arrendatario / Cliente:",
    firmaRep: "Firma del Representante del Arrendador:",
    fecha: "Fecha:",
    contratoNo: "Contrato N.º",
    imprimir: "Imprimir contrato",
    firmadoDigitalmente: "Firmado digitalmente el",
    pendienteFirma: "(pendiente de firma)",
  },
  en: {
    titulo: "MOTORCYCLE RENTAL AGREEMENT",
    nombreCliente: "Customer Name:",
    pasaporte: "Passport/ID #:",
    telefono: "Phone:",
    hotel: "Staying at Hotel:",
    s1: "1. Rental Terms",
    s1txt: "The Lessor agrees to rent the motorcycle to the Lessee under the following conditions:",
    marcaModelo: "Make/Model:",
    placa: "License Plate Number:",
    horaAlquiler: "Pickup Time:",
    fechaAlquiler: "Rental Date:",
    fechaDevolucion: "Return Date:",
    tarifaAplicada: "Rate Applied:",
    usd: "USD",
    totalEstimado: "Total due:",
    reglaDia: "Day rate",
    reglaEspecial: "Special rate (pickup after 2:00 pm)",
    reglaNocturno: "Overnight fee ($10.00) + next day rate",
    reglaPorDias: (n) => `Day rate × ${n} day${n === 1 ? "" : "s"}`,
    reglaPorDiasConEspecial: (n) => `Special first-day rate + regular rate for the next ${n - 1} day${n - 1 === 1 ? "" : "s"}`,
    s2: "2. Lessee's Use and Responsibility",
    s2intro: "The Lessee agrees to:",
    s2items: [
      "Use the motorcycle in a responsible and safe manner.",
      "Obey all traffic laws and local regulations.",
      "Not operate the motorcycle under the influence of alcohol or prohibited substances.",
      "Always use the helmet provided by the Lessor.",
      "Not allow any other person to operate the motorcycle without prior authorization from the Lessor.",
      "Not participate in races, competitions, or dangerous activities with the motorcycle.",
      "Not use the motorcycle on unsuitable terrain that may cause mechanical or structural damage.",
    ],
    s3: "3. Responsibility for Damages, Fines, and Loss",
    s3items: [
      "The Lessee is responsible for any damage, loss, or malfunction suffered by the motorcycle during the rental period and must assume the costs of repair or replacement as applicable.",
      "The Lessee will be responsible for any fine, penalty, or citation imposed by traffic authorities due to infractions committed during the use of the motorcycle.",
      "In case of an accident, the Lessee must immediately inform the Lessor and the corresponding authorities.",
    ],
    s4: "4. Return of the Motorcycle",
    s4items: [
      "The motorcycle must be returned in the same condition in which it was received, on the agreed date and time.",
      "In case of a delay in return, additional charges will be applied according to the rental rate.",
    ],
    s5: "5. Limitation of Lessor's Liability",
    s5items: [
      "The Lessor is not responsible for any accident, injury, or damage suffered by the Lessee or third parties during the use of the motorcycle.",
      "The Lessee releases the Lessor from any claim or legal action arising from the use of the motorcycle.",
    ],
    s6: "6. Signature and Acceptance",
    s6txt: "By signing this agreement, the Lessee acknowledges having read and understood all the terms and conditions described herein and agrees to comply with them.",
    firmaCliente: "Lessee's / Customer's Signature:",
    firmaRep: "Lessor's Representative Signature:",
    fecha: "Date:",
    contratoNo: "Agreement No.",
    imprimir: "Print agreement",
    firmadoDigitalmente: "Digitally signed on",
    pendienteFirma: "(signature pending)",
  },
};

export const TEXTOS_FORM = {
  es: {
    tituloNueva: "Nueva renta",
    subNueva: "Completa tus datos y los de la moto que vas a rentar.",
    idiomaLabel: "Idioma / Language",
    faltanMotos: "No hay motos disponibles en este momento, por favor contacta al local.",
    nombreCliente: "Nombre del cliente",
    nombrePlaceholder: "Nombre completo",
    cedula: "Cédula / pasaporte",
    cedulaPlaceholder: "8-123-4567",
    telefono: "Teléfono",
    telefonoPlaceholder: "6000-0000",
    hotel: "Hotel donde se hospeda",
    hotelPlaceholder: "Nombre del hotel",
    pais: "País",
    paisPlaceholder: "País de origen",
    correo: "Correo electrónico",
    correoPlaceholder: "correo@ejemplo.com",
    moto: "Moto",
    motoPlaceholder: "Selecciona una moto",
    fechaEntrega: "Fecha de entrega",
    horaEntrega: "Hora de entrega",
    horaEntregaAyuda: "La hora de entrega determina la tarifa aplicable.",
    fechaPrevista: "Debe devolver la moto el",
    tarifaCalculada: "Tarifa aplicada",
    totalEstimado: "Total estimado",
    notas: "Notas (opcional)",
    notasPlaceholder: "Condición de la moto, acuerdos, etc.",
    fotoLabel: "Foto del carnet de conducir",
    subirFoto: "Subir foto",
    tomarFoto: "Tomar foto",
    cambiarFoto: "Cambiar foto",
    procesandoImagen: "Procesando imagen…",
    continuar: "Continuar a términos y firma",
    errorNombreCedula: "El nombre y la cédula del cliente son obligatorios.",
    errorMoto: "Selecciona una moto disponible.",
    errorHora: "Indica la hora de entrega.",
    errorFecha: "Indica la fecha en que debe devolver la moto.",
    errorFoto: "Sube una foto del carnet de conducir del cliente.",
    tituloFirma: "Términos, condiciones y firma",
    subFirma: "Lee el contrato completo antes de firmar.",
    acepto: "He leído y acepto los términos y condiciones de este contrato.",
    firmarAqui: "Firma (dibuja con el dedo o el mouse)",
    limpiar: "Limpiar firma",
    atras: "Atrás",
    confirmarFirma: "Confirmar y firmar renta",
    guardando: "Guardando…",
    errorAcepto: "Debes aceptar los términos y condiciones.",
    errorFirma: "Falta la firma.",
    exitoTitulo: "¡Listo! Tu renta quedó registrada.",
    exitoTexto: "El local ya tiene tus datos, el contrato firmado y la foto de tu carnet. Preséntate a recoger la moto en la fecha acordada.",
    otraRenta: "Registrar otra renta",
  },
  en: {
    tituloNueva: "New rental",
    subNueva: "Fill in your details and the motorcycle you're renting.",
    idiomaLabel: "Idioma / Language",
    faltanMotos: "No motorcycles available right now, please contact the shop.",
    nombreCliente: "Customer name",
    nombrePlaceholder: "Full name",
    cedula: "ID / passport",
    cedulaPlaceholder: "ID or passport number",
    telefono: "Phone",
    telefonoPlaceholder: "Phone number",
    hotel: "Staying at hotel",
    hotelPlaceholder: "Hotel name",
    pais: "Country",
    paisPlaceholder: "Country of origin",
    correo: "Email",
    correoPlaceholder: "email@example.com",
    moto: "Motorcycle",
    motoPlaceholder: "Select a motorcycle",
    fechaEntrega: "Rental date",
    horaEntrega: "Pickup time",
    horaEntregaAyuda: "The pickup time determines the applicable rate.",
    fechaPrevista: "Must return the motorcycle on",
    tarifaCalculada: "Rate applied",
    totalEstimado: "Estimated total",
    notas: "Notes (optional)",
    notasPlaceholder: "Motorcycle condition, agreements, etc.",
    fotoLabel: "Driver's license photo",
    subirFoto: "Upload photo",
    tomarFoto: "Take photo",
    cambiarFoto: "Change photo",
    procesandoImagen: "Processing image…",
    continuar: "Continue to terms and signature",
    errorNombreCedula: "The customer's name and ID are required.",
    errorMoto: "Select an available motorcycle.",
    errorHora: "Enter the pickup time.",
    errorFecha: "Enter the date the motorcycle must be returned.",
    errorFoto: "Upload a photo of the customer's driver's license.",
    tituloFirma: "Terms, conditions and signature",
    subFirma: "Read the full agreement before signing.",
    acepto: "I have read and accept the terms and conditions of this agreement.",
    firmarAqui: "Signature (draw with finger or mouse)",
    limpiar: "Clear signature",
    atras: "Back",
    confirmarFirma: "Confirm and sign rental",
    guardando: "Saving…",
    errorAcepto: "You must accept the terms and conditions.",
    errorFirma: "Signature is missing.",
    exitoTitulo: "Done! Your rental has been recorded.",
    exitoTexto: "The shop now has your details, signed agreement, and license photo. Please arrive to pick up the motorcycle on the agreed date.",
    otraRenta: "Register another rental",
  },
};
